management:
  endpoints:
    web:
      exposure:
        include: '*'

# H2 connection
spring:
  application:
    name: spring-boot-kotlin-microservice
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect

url:
  products: "http://localhost:8080/"

logging:
  file:
    name: example.log

swagger:
  server-url: /